name=testi;rows=14;tracks=6;bpm=280;library=instruments.csv
;;;;;
kilkuttimet:hi hat;;;;;
;;kilkuttimet:block;;;
kilkuttimet:hi hat;kilkuttimet:hi hat 2;;;;
;;;kilkuttimet:snare 2;;
kilkuttimet:hi hat;;;;;
;;kilkuttimet:block;;;
kilkuttimet:hi hat;kilkuttimet:hi hat 2;;;;
;;;kilkuttimet:snare 2;;
kilkuttimet:hi hat;;;;;
;;kilkuttimet:block;;;
kilkuttimet:hi hat;kilkuttimet:hi hat 2;;;;
;;;kilkuttimet:snare 2;kilkuttimet:agogo;
kilkuttimet:hi hat;;;;;
